Repository oshada97/Tourism-Site, pull requests merged in 2020-10, with the labels that each got.

#19 navbar1.css
  Tourism Site/navbar1.css
Labels: hacktoberfest-accepted

#20 navbar2.css
  Tourism Site/navbar2.css
Labels: hacktoberfest, hacktoberfest-accepted

#21 saf imgages
  Tourism Site/saf1.jpg
  Tourism Site/saf2.jpg
  Tourism Site/saf3.jpg
  Tourism Site/saf4.jpg
  Tourism Site/saf5.jpg
  Tourism Site/saf6.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#23 about.html
  Tourism Site/about.html
Labels: hacktoberfest, hacktoberfest-accepted

#25 contactus.html
  Tourism Site/contactus.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#24 contactus.html
  Tourism Site/contactus.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#27 main.html
  Tourism Site/main.html
Labels: hacktoberfest, hacktoberfest-accepted

#28 Update main.html
  Tourism Site/main.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#31 safari.css
  Tourism Site/safari.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#32 Update contactus.html
  Tourism Site/contactus.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#30 Update about.html
  Tourism Site/about.html
Labels: hacktoberfest, hacktoberfest-accepted

#29 Update main.html
  Tourism Site/main.html
Labels: hacktoberfest, hacktoberfest-accepted

#37 Update contactus.html
  Tourism Site/contactus.html
Labels: hacktoberfest, hacktoberfest-accepted

#36 contactus.html
  Tourism Site/contactus.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#40 contactus.html
  Tourism Site/contactus.html
Labels: hacktoberfest, hacktoberfest-accepted

#41 main.css
  Tourism Site/main.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#42 function birth display.htmlfunction birth display.html
  methods/function birth display.html
Labels: hacktoberfest, hacktoberfest-accepted, help wanted

#45 gallery.html
  Tourism Site/gallery.html
Labels: hacktoberfest, hacktoberfest-accepted

#46 about.html
  Tourism Site/about.html
Labels: hacktoberfest, hacktoberfest-accepted

#48 about.html
  Tourism Site/about.html
Labels: hacktoberfest, hacktoberfest-accepted

#49 Update CONTRIBUTING.md
  CONTRIBUTING.md
  methods/redirecting.html
Labels: hacktoberfest, hacktoberfest-accepted

#50 Update safari.html
  Tourism Site/safari.html
Labels: hacktoberfest, hacktoberfest-accepted

#52 function birth display.html
  methods/function birth display.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#51 function birth display.html
  methods/function birth display.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#53 main.html
  Tourism Site/main.html
Labels: hacktoberfest, hacktoberfest-accepted

#54 safari.html
  Tourism Site/safari.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#55 safari.html
  Tourism Site/safari.html
Labels: hacktoberfest, hacktoberfest-accepted

#56 function birth display.html
  methods/function birth display.html
Labels: hacktoberfest, hacktoberfest-accepted

#59 Update Contributors.txt
  Contributors.txt
Labels: hacktoberfest, hacktoberfest-accepted

#60 to do list.html input
  Tourism Site/todo list for tourism site/to do list.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#61 style todo.css
  Tourism Site/todo list for tourism site/style todo.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#62 meta.html t1
  components for toursim site/meta tags/meta.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#63 php url validator
  components for toursim site/php url validator/php url validator.php
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#65 additional vehicle site for tourism site
  additional vehicle site for tourism site/databases/db.opt
  additional vehicle site for tourism site/databases/info_table.frm
  additional vehicle site for tourism site/databases/info_table.ibd
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#66 c panel.css
  additional vehicle site for tourism site/c panel.css
Labels: hacktoberfest, hacktoberfest-accepted

#67 c panel.php
  additional vehicle site for tourism site/c panel.php
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#68 c panel.css extra
  additional vehicle site for tourism site/c panel.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#69 photos for vehicle site 1
  additional vehicle site for tourism site/1.jpg
  additional vehicle site for tourism site/2.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#70 dbcon.php
  additional vehicle site for tourism site/dbcon.php
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#71 index.php
  additional vehicle site for tourism site/index.php
Labels: hacktoberfest, hacktoberfest-accepted

#72 index.css
  additional vehicle site for tourism site/index.css
Labels: hacktoberfest, hacktoberfest-accepted

#73 delete.php
  additional vehicle site for tourism site/delete.php
Labels: hacktoberfest, hacktoberfest-accepted

#75 delete_form.php
  additional vehicle site for tourism site/delete_form.php
Labels: hacktoberfest, hacktoberfest-accepted

#76 slideshow.php
  additional vehicle site for tourism site/slideshow.php
Labels: hacktoberfest, hacktoberfest-accepted

#77 display.php
  additional vehicle site for tourism site/display.php
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#79 photos for vehicle site 2 - buddhika2002
  additional vehicle site for tourism site/car1.jpg
  additional vehicle site for tourism site/car2.jpg
  additional vehicle site for tourism site/car3.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#80 members.php
  additional vehicle site for tourism site/members.php
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#81 form.php
  additional vehicle site for tourism site/form.php
Labels: hacktoberfest, hacktoberfest-accepted

#82 logo.php
  additional vehicle site for tourism site/logo.php
Labels: hacktoberfest, hacktoberfest-accepted

#83 insert.php
  additional vehicle site for tourism site/insert.php
Labels: hacktoberfest, hacktoberfest-accepted

#84 insert_form.php
  additional vehicle site for tourism site/insert_form.php
Labels: hacktoberfest, hacktoberfest-accepted

#87 Update style.css
  Tourism Site/css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#88 update.php
  additional vehicle site for tourism site/update.php
Labels: hacktoberfest, hacktoberfest-accepted

#89 update_form.php
  additional vehicle site for tourism site/update_form.php
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#90 favicon.png
  additional vehicle site for tourism site/favicon.png
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#91 update_con- Copy.php
  additional vehicle site for tourism site/update_con- Copy.php
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#92 INSTRUSCTIONS.md
  additional vehicle site for tourism site/INSTRUSCTIONS.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#86 Dilshan Ramesh
  Contributors.txt
Labels: hacktoberfest-accepted

#98 pasindu
  Contributors.md
  Contributors.txt
Labels: hacktoberfest, hacktoberfest-accepted
